export { default as OpeningBackground } from './opening/Background'
export { default as Quotes } from './quotes/Quotes'
export { default as Gallery } from './gallery/Gallery'
export { default as Pesan } from './pesan/Pesan'
export { default as Carousel } from './carousel/Carousel'
export { default as Footer } from './footer/Footer'